import fs from "fs"
import { Paths, Schemas } from "./types"
import generateActions from "./generate-actions"
import generateSchemas, { generateSchemasImports } from "./generate-schemas"

const dir = "out"
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir)
}

function autoGeneratedCaution() {
  let result = ""

  result += "/**\n"
  result += " * \n"
  result += " * This is auto-generated file.\n"
  result += " * All edits will not be preserved for the next generation.\n"
  result += " * \n"
  result += " * GitHub: https://github.com/FrameMuse/swagger-export-rfl\n"
  result += " * \n"
  result += "*/\n"
  result += "\n"

  return result
}

/* Paths */

{
  const file = fs.openSync(dataOutDir + "/actions.ts", "w")
  fs.writeSync(file, autoGeneratedCaution())
  fs.writeSync(file, `import { Action } from "../client.types"`)
  fs.writeSync(file, `\n`)
  fs.writeSync(file, generateSchemasImports(schemas))
  fs.writeSync(file, `\n`)
  fs.writeSync(file, generateActions(paths))
  fs.closeSync(file)
}

/* Schemas */

{
  const file = fs.openSync(dataOutDir + "/schemas.ts", "w")
  fs.writeSync(file, autoGeneratedCaution())
  fs.writeSync(file, generateSchemas(schemas))
  fs.closeSync(file)
}
